ForumApp/flaskeddit/community/forms.py
import re

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, ValidationError

from flaskeddit import db
from flaskeddit.models import Community


class CommunityForm(FlaskForm):
    """Form for creating a new community."""

    name = StringField("Name", validators=[DataRequired()])
    description = TextAreaField("Description", validators=[DataRequired()])
    submit = SubmitField("Create")

    def validate_name(self, name):
        """
        Validates that a given community name does not contain a space and is not taken
        by an existing community in the database.
        """
        if re.search(" ", name.data):
            raise ValidationError("Name cannot contain a space.")

        community = Community.query.filter(
            db.func.lower(Community.name) == name.data.lower()
        ).first()
        if community is not None:
            raise ValidationError("Name is already taken.")


class UpdateCommunityForm(FlaskForm):
    """Form for updating a community description."""

    description = TextAreaField("Description", validators=[DataRequired()])
    submit = SubmitField("Update")

ForumApp/flaskeddit/post/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import IntegerField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, ValidationError

from flaskeddit.models import Post


class PostForm(FlaskForm):
    """Form for creating a new post."""

    title = StringField("Title", validators=[DataRequired()])
    post = TextAreaField("Post", validators=[DataRequired()])
    community_id = IntegerField("Community Id", validators=[DataRequired()])
    submit = SubmitField("Create")

    def validate_title(self, title):
        """
        Validates that a given title is not already taken by an existing post within
        the target community in the database.
        """
        post = Post.query.filter_by(
            title=title.data, community_id=self.community_id.data
        ).first()
        if post is not None:
            raise ValidationError(
                "Post with same title already exists within this community."
            )


class UpdatePostForm(FlaskForm):
    """Form for updating a post."""

    post = TextAreaField("Post", validators=[DataRequired()])
    submit = SubmitField("Create")

ForumApp/flaskeddit/communities/__init__.py
from flask import Blueprint

communities_blueprint = Blueprint("communities", __name__)

from flaskeddit.communities import routes

ForumApp/flaskeddit/communities/routes.py
from flask import render_template, request

from flaskeddit.communities import communities_blueprint, communities_service


@communities_blueprint.route("/communities")
def communities():
    """
    Route for page displaying list of all communities sorted by date created.
    """
    page = int(request.args.get("page", 1))
    communities = communities_service.get_communities(page)
    return render_template("communities.jinja2", tab="recent", communities=communities)


@communities_blueprint.route("/communities/top")
def top_communities():
    """
    Route for page displaying list of all communities sorted by most members.
    """
    page = int(request.args.get("page", 1))
    communities = communities_service.get_communities_by_membership(page)
    return render_template("communities.jinja2", tab="top", communities=communities)

ForumApp/flaskeddit/community/__init__.py
from flask import Blueprint

community_blueprint = Blueprint("community", __name__)

from flaskeddit.community import routes

ForumApp/flaskeddit/community/routes.py
from flask import abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from flaskeddit.community import community_blueprint, community_service
from flaskeddit.community.forms import CommunityForm, UpdateCommunityForm


@community_blueprint.route("/community/<string:name>")
def community(name):
    """
    Route for page displaying a community and its posts sorted by date created.
    """
    page = int(request.args.get("page", 1))
    community = community_service.get_community(name)
    if community:
        posts = community_service.get_community_posts(community.id, page, False)
        community_member = None
        if current_user.is_authenticated:
            community_member = community_service.get_community_member(
                community.id, current_user.id
            )
        return render_template(
            "community.jinja2",
            tab="recent",
            community=community,
            posts=posts,
            community_member=community_member,
        )
    else:
        abort(404)


@community_blueprint.route("/community/<string:name>/top")
def top_community(name):
    """
    Route for page displaying a community and its posts sorted by number of upvotes.
    """
    page = int(request.args.get("page", 1))
    community = community_service.get_community(name)
    if community:
        posts = community_service.get_community_posts(community.id, page, True)
        community_member = None
        if current_user.is_authenticated:
            community_member = community_service.get_community_member(
                community.id, current_user.id
            )
        return render_template(
            "community.jinja2",
            tab="top",
            community=community,
            posts=posts,
            community_member=community_member,
        )
    else:
        abort(404)


@community_blueprint.route("/community/create", methods=["GET", "POST"])
@login_required
def create_community():
    """
    Route for creating a community. On a GET request, it returns the community creation
    form. On a POST request, it processes a community creation.
    """
    form = CommunityForm()
    if form.validate_on_submit():
        community_service.create_community(
            form.name.data, form.description.data, current_user
        )
        flash("Successfully created community.", "primary")
        return redirect(url_for("community.community", name=form.name.data))
    return render_template("create_community.jinja2", form=form)


@community_blueprint.route("/community/<string:name>/update", methods=["GET", "POST"])
@login_required
def update_community(name):
    """
    Route for updating a community description. On a GET request, it returns the update
    community form. On a POST request, it processes the community update.
    """
    community = community_service.get_community(name)
    if community:
        if community.user_id != current_user.id:
            return redirect(url_for("community.community", name=name))
        form = UpdateCommunityForm()
        if form.validate_on_submit():
            community_service.update_community(community, form.description.data)
            flash("Successfully updated community.", "primary")
            return redirect(url_for("community.community", name=name))
        form.description.data = community.description
        return render_template("update_community.jinja2", name=name, form=form)
    else:
        abort(404)


@community_blueprint.route("/community/<string:name>/delete", methods=["POST"])
@login_required
def delete_community(name):
    """
    Route that handles deleting a community.
    """
    community = community_service.get_community(name)
    if community:
        if community.user_id != current_user.id:
            return redirect(url_for("community.community", name=name))
        community_service.delete_community(community)
        flash("Successfully deleted community.", "primary")
        return redirect(url_for("feed.feed"))
    else:
        abort(404)


@community_blueprint.route("/community/<string:name>/join", methods=["POST"])
@login_required
def join_community(name):
    """
    Route that handles adding the current user as a community member.
    """
    community = community_service.get_community(name)
    if community:
        community_member = community_service.get_community_member(
            community.id, current_user.id
        )
        if community_member == None:
            community_service.create_community_member(community, current_user)
        flash("Successfully joined community.", "primary")
        return redirect(url_for("community.community", name=community.name))
    else:
        abort(404)


@community_blueprint.route("/community/<string:name>/leave", methods=["POST"])
@login_required
def leave_community(name):
    """
    Route that handles removing the current user as a community member.
    """
    community = community_service.get_community(name)
    if community:
        community_member = community_service.get_community_member(
            community.id, current_user.id
        )
        if community_member:
            community_service.delete_community_member(community_member)
        flash("Successfully left community.", "primary")
        return redirect(url_for("community.community", name=community.name))
    else:
        abort(404)

ForumApp/flaskeddit/feed/__init__.py
from flask import Blueprint

feed_blueprint = Blueprint("feed", __name__)

from flaskeddit.feed import routes

ForumApp/flaskeddit/feed/routes.py
from flask import render_template, request
from flask_login import current_user

from flaskeddit.feed import feed_blueprint, feed_service


@feed_blueprint.route("/")
@feed_blueprint.route("/feed")
def feed():
    """
    Route for displaying posts from the current user's joined communities sorted by
    date created.
    """
    page = int(request.args.get("page", 1))
    if current_user.is_authenticated:
        posts = feed_service.get_feed(current_user, page, False)
        return render_template("feed.jinja2", tab="recent", posts=posts)
    else:
        return render_template("feed.jinja2", tab="recent", posts=None)


@feed_blueprint.route("/feed/top")
def top_feed():
    """
    Route for displaying posts from the current user's joined communities sorted by
    upvotes.
    """
    page = int(request.args.get("page", 1))
    if current_user.is_authenticated:
        posts = feed_service.get_feed(current_user, page, True)
        return render_template("feed.jinja2", tab="top", posts=posts)
    else:
        return render_template("feed.jinja2", tab="top", posts=None)

ForumApp/flaskeddit/post/__init__.py
from flask import Blueprint

post_blueprint = Blueprint("post", __name__)

from flaskeddit.post import routes

ForumApp/flaskeddit/post/routes.py
from flask import abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from flaskeddit.community import community_service
from flaskeddit.post import post_blueprint, post_service
from flaskeddit.post.forms import PostForm, UpdatePostForm


@post_blueprint.route("/community/<string:name>/post/<string:title>")
def post(name, title):
    """
    Route for page displaying a post and its replies sorted by date created.
    """
    page = int(request.args.get("page", 1))
    post = post_service.get_post_with_votes(title, name)
    if post:
        replies = post_service.get_post_replies(post.id, page, False)
        return render_template("post.jinja2", tab="recent", post=post, replies=replies)
    else:
        abort(404)


@post_blueprint.route("/community/<string:name>/post/<string:title>/top")
def top_post(name, title):
    """
    Route for page displaying a post and its replies sorted by upvotes.
    """
    page = int(request.args.get("page", 1))
    post = post_service.get_post_with_votes(title, name)
    if post:
        replies = post_service.get_post_replies(post.id, page, True)
        return render_template("post.jinja2", tab="top", post=post, replies=replies)
    else:
        abort(404)


@post_blueprint.route("/community/<string:name>/post/create", methods=["GET", "POST"])
@login_required
def create_post(name):
    """
    Route for creating a post. On a GET request, it returns the post creation form. On
    a POST request, it handles creating a post.
    """
    community = community_service.get_community(name)
    if community:
        form = PostForm()
        form.community_id.data = community.id
        if form.validate_on_submit():
            post_service.create_post(
                form.title.data, form.post.data, community, current_user
            )
            flash("Successfully created post.", "primary")
            return redirect(url_for("post.post", name=name, title=form.title.data))
        return render_template("create_post.jinja2", name=name, form=form)
    else:
        abort(404)


@post_blueprint.route(
    "/community/<string:name>/post/<string:title>/update", methods=["GET", "POST"]
)
@login_required
def update_post(name, title):
    """
    Route for updating a post. On a GET request, it returns the post update form. On a
    POST request, it handles updating a post.
    """
    post = post_service.get_post(title, name)
    if post:
        if post.user_id != current_user.id:
            return redirect(url_for("post.post", name=name, title=title))
        form = UpdatePostForm()
        if form.validate_on_submit():
            post_service.update_post(post, form.post.data)
            flash("Successfully updated post.", "primary")
            return redirect(url_for("post.post", name=name, title=title))
        form.post.data = post.post
        return render_template("update_post.jinja2", name=name, title=title, form=form)
    else:
        abort(404)


@post_blueprint.route(
    "/community/<string:name>/post/<string:title>/delete", methods=["POST"]
)
@login_required
def delete_post(name, title):
    """
    Route that handles deleting a post.
    """
    post = post_service.get_post(title, name)
    if post:
        if post.user_id != current_user.id:
            return redirect(url_for("post.post", name=name, title=title))
        post_service.delete_post(post)
        flash("Successfully deleted post.", "primary")
        return redirect(url_for("community.community", name=name))
    else:
        abort(404)


@post_blueprint.route(
    "/community/<string:name>/post/<string:title>/upvote", methods=["POST"]
)
@login_required
def upvote_post(name, title):
    """
    Route that handles upvoting a post as the current user.
    """
    post = post_service.get_post(title, name)
    if post:
        post_service.upvote_post(post.id, current_user.id)
        return redirect(request.referrer)
    else:
        abort(404)


@post_blueprint.route(
    "/community/<string:name>/post/<string:title>/downvote", methods=["POST"]
)
@login_required
def downvote_post(name, title):
    """
    Route that handles downvoting a post as the current user.
    """
    post = post_service.get_post(title, name)
    if post:
        post_service.downvote_post(post.id, current_user.id)
        return redirect(request.referrer)
    else:
        abort(404)

ForumApp/flaskeddit/user/__init__.py
from flask import Blueprint

user_blueprint = Blueprint("user", __name__)

from flaskeddit.user import routes

ForumApp/flaskeddit/user/routes.py
from flask import render_template

from flaskeddit.user import user_blueprint, user_service


@user_blueprint.route("/user/<string:username>")
def app_user(username):
    """
    Route displaying a user's profile page.
    """
    user = user_service.get_user(username)
    return render_template("user.jinja2", app_user=user)

ForumApp/flaskeddit/templates/communities.jinja2
{% extends "layout.jinja2" %} {% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% if tab == "recent" %}
      <li class="breadcrumb-item active" aria-current="page">Recent</li>
      <li class="breadcrumb-item">
        <a href="{{ url_for('communities.top_communities') }}">Top</a>
      </li>
    {% elif tab == "top" %}
      <li class="breadcrumb-item">
        <a href="{{ url_for('communities.communities') }}">Recent</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">Top</li>
    {% endif %}
  </ol>
</nav>
<h2 class="mb-3">Communities</h2>
<div class="row">
  <div class="col-8">
    {% for community in communities.items %}
      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">
            <a
              class="text-dark"
              href="{{ url_for('community.community', name=community.name) }}"
              >f/{{ community.name }}</a
            >
          </h5>
          <h6 class="card-subtitle text-muted">
            <small
              >Created on {{ community.date_created.strftime("%m/%d/%Y") }} by
              <a
                class="text-muted"
                href="{{ url_for('user.app_user', username=community.username) }}"
                >u/{{ community.username }}</a
              ></small
            >
          </h6>
        </div>
      </div>
    {% endfor %}
    <nav class="my-2" aria-label="Page navigation example">
      <ul class="pagination">
        {% if communities.prev_num %}
          <li class="page-item">
            <a class="page-link" href="?page={{ communities.prev_num }}"
              >Previous</a
            >
          </li>
        {% endif %}
        {% if communities.next_num %}
          <li class="page-item">
            <a class="page-link" href="?page={{ communities.next_num }}">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        Communities
      </div>
      <div class="card-body">
        <p class="card-text">
          Find a topic you're interested in or create one
          for yourself.
        </p>
        <a
          href="{{ url_for('community.create_community') }}"
          class="btn btn-sm btn-primary"
          >Create</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}

ForumApp/flaskeddit/templates/community.jinja2
{% extends "layout.jinja2" %} {% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% if tab == "recent" %}
      <li class="breadcrumb-item active" aria-current="page">Recent</li>
      <li class="breadcrumb-item">
        <a href="{{ url_for('community.top_community', name=community.name) }}"
          >Top</a
        >
      </li>
    {% elif tab == "top" %}
      <li class="breadcrumb-item">
        <a href="{{ url_for('community.community', name=community.name) }}"
          >Recent</a
        >
      </li>
      <li class="breadcrumb-item active" aria-current="page">Top</li>
    {% endif %}
  </ol>
</nav>
<h2 class="mb-3">f/{{ community.name }}</h2>
<div class="row">
  <div class="col-8">
    {% for post in posts.items %}
      <div class="card mb-2">
        <div class="row">
          <div class="col-2">
            <ul class="list-group text-center border-0">
              <li class="list-group-item py-1 border-0">
                <form
                  action="{{ url_for('post.upvote_post', name=community.name, title=post.title) }}"
                  method="POST"
                >
                  <small
                    ><input
                      class="border-0"
                      type="submit"
                      value="▲"
                      {% if not current_user.is_authenticated %}disabled{% endif %}
                  /></small>
                </form>
              </li>
              <li class="list-group-item py-1 border-0">
                <small>{{ post.votes }}</small>
              </li>
              <li class="list-group-item py-1 border-0">
                <form
                  action="{{ url_for('post.downvote_post', name=community.name, title=post.title) }}"
                  method="POST"
                >
                  <small
                    ><input
                      class="border-0"
                      type="submit"
                      value="▼"
                      {% if not current_user.is_authenticated %}disabled{% endif %}
                  /></small>
                </form>
              </li>
            </ul>
          </div>
          <div class="col-10">
            <div class="card-body">
              <h5 class="card-title">
                <a
                  class="text-dark"
                  href="{{ url_for('post.post', name=community.name, title=post.title) }}"
                  >{{ post.title }}</a
                >
              </h5>
              <h6 class="card-subtitle text-muted">
                <small
                  >Posted on {{ post.date_created.strftime("%m/%d/%Y") }} by
                  <a
                    class="text-muted"
                    href="{{ url_for('user.app_user', username=post.username) }}"
                    >u/{{ post.username }}</a
                  ></small
                >
              </h6>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    <nav class="my-2" aria-label="Page navigation example">
      <ul class="pagination">
        {% if posts.prev_num %}
          <li class="page-item">
            <a class="page-link" href="?page={{ posts.prev_num }}">Previous</a>
          </li>
        {% endif %}
        {% if posts.next_num %}
          <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_num }}">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        Community Details
      </div>
      <div class="card-body">
        <p class="card-text">
          {{ community.description }}
        </p>
        <div class="container-fluid">
          <div class="row">
            <a
              href="{{ url_for('post.create_post', name=community.name) }}"
              class="btn btn-sm btn-primary mb-1"
              >Post</a
            >
          </div>
          {% if current_user.is_authenticated and community_member != None %}
            <div class="row">
              <form
                action="{{ url_for('community.leave_community', name=community.name) }}"
                method="POST"
              >
                <button class="btn btn-sm btn-primary mb-1">
                  Leave
                </button>
              </form>
            </div>
          {% elif current_user.is_authenticated %}
            <div class="row">
              <form
                action="{{ url_for('community.join_community', name=community.name) }}"
                method="POST"
              >
                <button class="btn btn-sm btn-primary mb-1">
                  Join
                </button>
              </form>
            </div>
          {% endif %}
          {% if current_user.is_authenticated and current_user.id == community.user_id %}
            <div class="row">
              <a
                href="{{ url_for('community.update_community', name=community.name) }}"
                class="btn btn-sm btn-primary mb-1"
                >Update</a
              >
            </div>
            <div class="row">
              <form
                action="{{ url_for('community.delete_community', name=community.name) }}"
                method="POST"
              >
                <button class="btn btn-sm btn-danger mb-1">
                  Delete
                </button>
              </form>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

ForumApp/flaskeddit/templates/create_community.jinja2
{% extends "layout.jinja2" %} {% block content %}
<h2 class="mb-3">Create Community</h2>
<form action="{{ url_for('community.create_community') }}" method="POST">
  {{ form.csrf_token }}
  <div class="form-group">
    {{ form.name.label }}
    {% if form.name.errors %}
      {{ form.name(class="form-control is-invalid") }}
      {% for error in form.name.errors %}
        <div class="invalid-feedback">
          {{ error }}
        </div>
      {% endfor %}
    {% else %}
      {{ form.name(class="form-control") }}
    {% endif %}
  </div>
  <div class="form-group">
    {{ form.description.label }}
    {{ form.description(class="form-control") }}
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock %}

ForumApp/flaskeddit/templates/post.jinja2
{% extends "layout.jinja2" %} {% block content %}
<h2 class="mb-3">{{ post.title }}</h2>
<div class="row">
  <div class="col-8">
    <div class="card mb-2">
      <div class="row">
        <div class="col-2">
          <ul class="list-group text-center border-0">
            <li class="list-group-item py-1 my-1 border-0">
              <form
                action="{{ url_for('post.upvote_post', name=post.community_name, title=post.title) }}"
                method="POST"
              >
                <small
                  ><input
                    class="border-0"
                    type="submit"
                    value="▲"
                    {% if not current_user.is_authenticated %}disabled{% endif %}
                /></small>
              </form>
            </li>
            <li class="list-group-item py-1 my-1 border-0">
              <small>{{ post.votes }}</small>
            </li>
            <li class="list-group-item py-1 my-1 border-0">
              <form
                action="{{ url_for('post.downvote_post', name=post.community_name, title=post.title) }}"
                method="POST"
              >
                <small
                  ><input
                    class="border-0"
                    type="submit"
                    value="▼"
                    {% if not current_user.is_authenticated %}disabled{% endif %}
                /></small>
              </form>
            </li>
          </ul>
        </div>
        <div class="col-10">
          <div class="card-body">
            <h4 class="card-title">
              {{ post.title }}
            </h4>
            <h6 class="card-subtitle text-muted mb-3">
              <small
                >Posted on {{ post.date_created.strftime("%m/%d/%Y") }} by
                <a
                  class="text-muted"
                  href="{{ url_for('user.app_user', username=post.username) }}"
                  >u/{{ post.username }}</a
                >
              </small>
            </h6>
            <p class="card-text">
              {{ post.post }}
            </p>
          </div>
        </div>
      </div>
    </div>
    <p class="text-muted ml-1">
      Sort by:
      {% if tab == "recent" %}
        Recent /
        <a
          href="{{ url_for('post.top_post', name=post.community_name, title=post.title) }}"
          >Top</a
        >
      {% elif tab == "top" %}
        <a
          href="{{ url_for('post.post', name=post.community_name, title=post.title) }}"
          >Recent</a
        >
        / Top
      {% endif %}
    </p>
    <hr />
    {% for reply in replies.items %}
      <div class="card mb-2">
        <div class="row">
          <div class="col-2">
            <ul class="list-group text-center border-0">
              <li class="list-group-item py-1 border-0">
                <form
                  action="{{ url_for('reply.upvote_reply', name=post.community_name, title=post.title, reply_id=reply.id) }}"
                  method="POST"
                >
                  <small
                    ><input
                      class="border-0"
                      type="submit"
                      value="▲"
                      {% if not current_user.is_authenticated %}disabled{% endif %}
                  /></small>
                </form>
              </li>
              <li class="list-group-item py-1 border-0">
                <small>{{ reply.votes }}</small>
              </li>
              <li class="list-group-item py-1 border-0">
                <form
                  action="{{ url_for('reply.downvote_reply', name=post.community_name, title=post.title, reply_id=reply.id) }}"
                  method="POST"
                >
                  <small
                    ><input
                      class="border-0"
                      type="submit"
                      value="▼"
                      {% if not current_user.is_authenticated %}disabled{% endif %}
                  /></small>
                </form>
              </li>
            </ul>
          </div>
          <div class="col-10">
            <div class="card-body">
              <p class="card-text">
                {{ reply.reply }}
              </p>
              <h6 class="card-subtitle text-muted">
                <small
                  >Replied on {{ reply.date_created.strftime("%m/%d/%Y") }} by
                  <a
                    class="text-muted"
                    href="{{ url_for('user.app_user', username=reply.username) }}"
                    >u/{{ reply.username }}</a
                  >
                  {% if current_user.is_authenticated and current_user.id == reply.user_id %}
                    &#183;
                    <a
                      class="text-muted"
                      href="{{ url_for('reply.update_reply', name=post.community_name, title=post.title, reply_id=reply.id) }}"
                      >Edit</a
                    >
                  {% endif %}
                </small>
              </h6>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    <nav class="my-2" aria-label="Page navigation example">
      <ul class="pagination">
        {% if replies.prev_num %}
          <li class="page-item">
            <a class="page-link" href="?page={{ replies.prev_num }}">Previous</a>
          </li>
        {% endif %}
        {% if replies.next_num %}
          <li class="page-item">
            <a class="page-link" href="?page={{ replies.next_num }}">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        <a
          class="text-dark"
          href="{{ url_for('community.community', name=post.community_name) }}"
          >f/{{ post.community_name }}</a
        >
      </div>
      <div class="card-body">
        <p class="card-text">
          {{ post.community_description }}
        </p>
        <div class="container-fluid">
          <div class="row">
            <a
              href="{{ url_for('reply.reply', name=post.community_name, title=post.title) }}"
              class="btn btn-sm btn-primary mb-1"
              >Reply</a
            >
          </div>
          {% if current_user.is_authenticated and current_user.id == post.user_id %}
            <div class="row">
              <a
                href="{{ url_for('post.update_post', name=post.community_name, title=post.title) }}"
                class="btn btn-sm btn-primary mb-1"
                >Update</a
              >
            </div>
            <div class="row">
              <form
                action="{{ url_for('post.delete_post', name=post.community_name, title=post.title) }}"
                method="POST"
              >
                <button class="btn btn-sm btn-danger">
                  Delete
                </button>
              </form>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

ForumApp/flaskeddit/templates/update_community.jinja2
{% extends "layout.jinja2" %} {% block content %}
<h2 class="mb-3">Update Community</h2>
<form
  action="{{ url_for('community.update_community', name=name) }}"
  method="POST"
>
  {{ form.csrf_token }}
  <div class="form-group">
    {{ form.description.label }}
    {{ form.description(class="form-control") }}
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock %}